const items = {
  Fruits: [
    'bananas',
    'apples',
    'grapes',
    'oranges',
    'strawberries',
    'avocados',
    'peaches',
    'pineapple',
    'pears',
  ],
  Vegetables: [
    'potatoes',
    'tomatoes',
    'onions',
    'carrots',
    'lettuce',
    'broccoli',
    'peppers',
    'celery',
    'garlic',
    'cucumbers',
  ],
  'Canned Goods': ['olives', 'soup', 'tuna', 'veggies', 'fruit'],
  'Frozen Foods': ['fish', 'ice cream', 'pizza', 'ready meals'],
  Meat: ['chicken', 'beef', 'pork', 'sausage'],
  'Fish and shellfish': ['shrimp', 'crab', 'clams', 'salmon', 'tilapia'],
  Deli: ['chees', 'ham', 'turkey', 'salami'],
  'Condiments & Spices': [
    'salt',
    'sugar',
    'pepper',
    'oregano',
    'cinnamon',
    'ketchup',
    'mayonnaise',
    'mustard ',
  ],
  'Sauces & Oils': ['olive oil', 'tomato sauce', 'hot sauce', 'soy sauce'],
  Snacks: ['chips', 'crackers', 'pretzels', 'popcorn', 'peanuts', 'nuts', 'candy'],
  'Bread & Bakery': [
    'whole wheat',
    'white',
    'italian',
    'sandwich',
    'tortillas',
    'pies',
    'muffins',
    'bagels',
    'cookies',
  ],
  Beverages: ['water', 'coffe', 'milk', 'juice', 'soda', 'tea', 'beer', 'wine'],
  'Pasta/Rice': ['spaghetti', 'macaroni', 'noodles', 'white rice'],
  Cereal: ['oats', 'rice', 'wheat', 'granola'],
  Baking: ['flour', 'baking powder', 'butter', 'milk', 'eggs'],
  'Personal Care': [
    'shampoo',
    'conditioner',
    'soap',
    'deodorant',
    'toothpaste',
    'dental floss',
    'shaving cream',
    'razor blades',
  ],
  'Health Care': ['band-aid', 'hydrogen peroxide', 'alcohol', 'pain reliever', 'antacids'],
  'Paper & Wrap': ['toilet paper', 'paper towels', 'tissues', 'aluminum foil', 'zip bags'],
  'Household Supplies': [
    'detergent',
    'softener',
    'bleach',
    'dish soap',
    'air freshener',
    'gloves',
    'sponge',
    'trash bags',
    'batteries',
  ],
  'Baby Items': ['baby food', 'diapers', 'wet wipes', 'moisturizing lotion'],
};

const shoppingListDates = [
  '2021/06/11',
  '2021/06/15',
  '2021/06/18',
  '2021/07/10',
  '2021/07/12',
  '2021/07/15',
  '2021/07/19',
  '2021/07/20',
  '2021/07/25',
  '2021/08/05',
  '2021/09/02',
  '2021/09/19',
  '2021/09/23',
  '2021/09/24',
  '2021/09/27',
  '2021/09/29',
  '2021/10/07',
  '2021/11/01',
];

export { items, shoppingListDates };
